//! Levels, and what a level does.
//!
//! Two rules, both of them pure functions of the level, and both of them stated
//! here rather than anywhere they could drift.
//!
//! # The curve
//!
//! `xp_to_next(L) = round(20 · 1.35^(L−1))`, from `PLAN.md` 1.5. Computed once
//! into [`XP_TO_NEXT`] and read from the table thereafter, so nothing at runtime
//! does float arithmetic on a level-up — a level is a thing a player watches
//! happen, and a level that lands one experience point differently on one
//! machine is a save that disagrees with itself.
//!
//! # The rotation
//!
//! Each level adds one row to one grid, in the fixed order weapon, chest,
//! helmet, gloves, greaves. Fixed rather than chosen because it makes
//! [`rows_for`] a pure function of the level: a save carrying `level` implies
//! its board sizes and cannot disagree with them, and a save that has been
//! edited by hand is caught rather than believed.
//!
//! Skill nodes may grant rows out of turn. Those are recorded separately and
//! added on top, so the function stays pure — see [`board_rows`].

use crate::piece::SlotKind;

/// Rows every grid starts with.
///
/// Three, not the engine's eight. A Sprocketman climbs out of the pit with
/// almost nothing and grows into their frames; the creatures they fight keep
/// full boards, which is why the early game is spent outgunned in board area.
/// That is the intended shape of a grindy game rather than an oversight, and
/// `enemies.json` is the evidence they are not sharing this number.
pub const STARTING_ROWS: u8 = 3;

/// The largest grid a level-up will build to.
///
/// The engine's own `SLOT_H`. Beyond it the catalogue has nothing that needs
/// the room, and a board taller than the pieces is a board with a dead half.
pub const MAX_ROWS: u8 = crate::slot::SLOT_H;

/// Which grid each level grows, in order from level 2.
pub const ROTATION: [SlotKind; 5] = [
    SlotKind::Weapon,
    SlotKind::Chest,
    SlotKind::Helmet,
    SlotKind::Gloves,
    SlotKind::Greaves,
];

/// The highest level the table covers.
pub const MAX_LEVEL: usize = 32;

/// Experience from one level to the next, indexed by level − 1.
///
/// `XP_TO_NEXT[0]` is what level 1 costs to leave. Generated by the test
/// `the_table_matches_the_formula`, so the numbers here and the formula in the
/// plan cannot drift apart without something going red.
pub const XP_TO_NEXT: [i32; MAX_LEVEL] = [
    20, 27, 36, 49, 66, 90, 121, 163, 221, 298, 402, 543, 733, 989, 1336,
    1803, 2434, 3286, 4436, 5989, 8085, 10915, 14736, 19893, 26856, 36256,
    48945, 66076, 89202, 120423, 162571, 219471,
];

/// What it costs to leave `level`.
pub fn xp_to_next(level: u32) -> i32 {
    let i = (level.max(1) as usize - 1).min(MAX_LEVEL - 1);
    XP_TO_NEXT[i]
}

/// Total experience banked to reach `level` from level 1.
pub fn xp_to_reach(level: u32) -> i32 {
    (1..level.max(1)).map(xp_to_next).sum()
}

/// The level a total amount of banked experience buys.
pub fn level_for(total_xp: i32) -> u32 {
    let mut level = 1;
    let mut spent = 0;
    while (level as usize) < MAX_LEVEL {
        let need = xp_to_next(level);
        if total_xp - spent < need {
            break;
        }
        spent += need;
        level += 1;
    }
    level
}

/// How far through the current level a total stands: `(into, needed)`.
pub fn progress(total_xp: i32) -> (i32, i32) {
    let level = level_for(total_xp);
    (total_xp - xp_to_reach(level), xp_to_next(level))
}

/// **A level grows no board. M12.3 retired that, and it was an MVP pillar.**
///
/// `PLAN.md` M4 made board size a pure function of level and the rotation in
/// `ROTATION` decided which grid grew when. That was right while pieces were
/// scarce by accident: a row was the only thing that ever changed about a
/// board, so handing one out on a schedule was the whole of progression.
///
/// M12.0 measured what it costs once pieces are not scarce. **Fill goes
/// *down* as you level** — 43% at five, 37% at eight — because rows arrive on
/// a clock and components do not, so levelling dilutes you. A scheduled row is
/// dilution on a timer.
///
/// So a row is a thing you **earn** now: a skill point spent on it, or a quest
/// line finished. Every level poses the game's central question with the
/// player's own hands — power on the board you have, or a bigger board — and
/// pressure regulates itself instead of leaking away every fifth level.
///
/// **Nothing is banked to make this work**, which is a divergence from
/// `PLAN-M12.md` and the reason is that the save already carries it:
/// `BoardSave::rows` is written and restored verbatim and `resize_boards` only
/// ever grows, so an old file keeps every row it had without a ledger and
/// without a migration. What a row came *from* is derived — from
/// `skills_taken` and from `quests_done` — the same way a node's effect and a
/// tower's fallen floors are.
pub fn base_rows() -> u8 {
    STARTING_ROWS
}

/// Rows this grid has: the base, plus everything earned for it.
pub fn board_rows(granted: u8) -> u8 {
    (STARTING_ROWS + granted).min(MAX_ROWS)
}

/// How much experience beating this creature is worth.
///
/// The creature's rating on the shared scale, divided by [`XP_DIVISOR`]. Not a
/// hand-authored number per creature: a creature is worth what it is worth, and
/// `rating::creature_rating` is the one thing that knows.
///
/// The floor of one matters more than it looks. Early creatures rate well under
/// the divisor, so without it a rat would be worth nothing and the first hour
/// of the game would pay in zeroes.
pub fn xp_for_rating(rating: i32) -> i32 {
    (rating / XP_DIVISOR).max(1)
}

/// Turns a creature's rating into experience.
///
/// **Set by `tests/progression.rs::level_five_lands_where_the_plan_says`, not
/// by taste.** The plan committed to level 5 arriving in 25–35 fights; that
/// test walks the shipped map and fails outside the band, so this number is a
/// measurement of the map rather than an opinion about it. Changing the map's
/// regions can move it, which is the point — the band is the contract and this
/// is what is tuned to hold it.
pub const XP_DIVISOR: i32 = 5;
